### ISSUE TITLE
[1.19.2] Hang on startup with I Wanna Skate

### ISSUE THREAD

**Issue by abundzu** [CCr4ft3r/lightspeed#17] opened 2023-04-26 23:40 UTC
Minecraft times out during startup with Lightspeed and I Wanna Skate (and citadel). Requires force close to kill client. Forge version 43.2.8.

[latest](https://mclo.gs/rAn7wyW)

**Comment by jahirxtrap** [comment] 2023-05-03 02:29
Same here

**Comment by CCr4ft3r** [comment] 2023-05-11 15:55
I fixed it. Thanks to @embeddedt for finding the cause. Will be included in 1.0.4

**Closed as completed by CCr4ft3r** 2023-05-11 15:55 UTC
