### ISSUE TITLE
Game crash on startup startup related to 1.0.2 

### ISSUE THREAD

**Issue by hansenjc** [CCr4ft3r/lightspeed#9] opened 2023-03-21 03:33 UTC
On the second run of starting the game with lightspeed 1.0.2 installed, the game crashes when starting. This issue is not present on 0.3.1.

[log](https://mclo.gs/kB6PwjC)

**Comment by CCr4ft3r** [comment] 2023-03-22 13:50
Thx for reporting it. I will fix it asap

**Comment by CCr4ft3r** [comment] 2023-03-23 16:35
This issue does not seems to be caused by lightspeed even execptions are thrown by Lightspeeds they should not cause crashing. Please try disabling Lightspeed and the crash should still occur.

If not please provide the crash-report.txt

**Comment by CCr4ft3r** [comment] 2023-03-26 12:32
This issue will be closed in one week if no further information is provided. If the problem still occur after closing this issue feel free to open a new one with all required information: MC version, Forge version, crash-report, latest.log/debug.log, minimal reproducable setup (mods, datapacks etc.).

**Closed as not planned** 2023-04-02 18:37 UTC
Labels: needs information
