### ISSUE TITLE
[1.18.2] Game wont start: Unable to bake model

### ISSUE THREAD

**Issue by DeshiDesu** [CCr4ft3r/lightspeed#14] opened 2023-04-06 00:20 UTC
My game hangs on the loading screen occasionally, but after restarting it loads as normal.

The last message displayed by my console:
[05/04/2023 19:59:33 p.m.] [Render thread/WARN] Unable to bake model: 'compatoplenty:willow_leaf_pile#down=false,east=false,north=true,south=true,up=false,waterlogged=false,west=true': java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513

This is just part of the several similar messages in my console logs.

Here is my full console log:
https://paste.atlauncher.com/view/bb984541-eb17-43c9-a3fd-8d95b54c7b38

**Comment by CCr4ft3r** [comment] 2023-04-13 15:38
I cannot reproduce it with some of the mods listed in the log. Please provide a minimal reproducable setup including the mods that are causing this stucking loading screen

**Comment by DeshiDesu** [comment] 2023-04-13 18:13
Sorry. I will try to do this when I can find the time.

**Comment by DeshiDesu** [comment] 2023-04-24 02:56
I'll drop this issue for now, might come back later to figure it out. I just have a lot of mods and it's a headache to go through all of them.

**Comment by DeshiDesu** [comment] 2023-04-25 21:58
I installed this mod again after uninstalling debugify, and now it loads normally without hanging. I have not tested with only debugify and lightspeed installed but maybe the issue is an incompatibility with debugify?

**Comment by CCr4ft3r** [comment] 2023-04-26 05:02
Alright, I will check if it's an incompatibility with Debugify.

**Comment by 1963915695** [comment] 2023-05-02 16:13
I have the same problem as you,but I didn't install the mod you mentioned.

**Comment by DeshiDesu** [comment] 2023-05-02 17:37
> I have the same problem as you,but I didn't install the mod you mentioned.

Can I see your mod list?

**Comment by tallubhai** [comment] 2023-05-10 22:34
Debugify has issues on 1.18.2, I had a constant crash on startup with it installed. Although @1963915695 had the issue without debugify, so it may not be the culprit.

**Comment by CCr4ft3r** [comment] 2023-05-11 15:53
duplicate of #17

**Closed as completed by CCr4ft3r** 2023-05-11 15:53 UTC
Labels: needs information
